version: "3.5"

services:
  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    volumes:
      - /opt/invite-backend-jenkins/jenkins_home/workspace/invite_prod_nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - network1
networks:
  network1:
    name: inviteapi-network
    external: true