version: "3.5"

services:
  nginx:
    image: nginx:alpine
    container_name: ${CONTAINER_NAME}
    volumes:
      - ${HOST_CONFIG_FILE}:/etc/nginx/conf.d/default.conf
    ports:
      - ${HOST_PORT}:80
    networks:
      - network1
networks:
  network1:
    name: ${NETWORK_NAME}
    external: true